
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABRE_PAR DIAGRAMA DOIS_PONTOS FECHA_PAR GERAL LIST MAIORQ MENORQ PALAVRA_CLASSES PALAVRA_RELACOES PONTO_VIRGULA PRIVACIDADE RETA TIPO TITULO VARIAVELprogram : comeco iniClassescomeco : TITULO DOIS_PONTOS VARIAVEL DIAGRAMA GERAL DOIS_PONTOSiniClasses : MENORQ MENORQ PALAVRA_CLASSES classes MAIORQ MAIORQclasses : classe\n    | classes classeclasse : VARIAVEL ABRE_PAR interno_classe FECHA_PAR PONTO_VIRGULA\n    interno_classe : atributos metodos_opt\n                   | metodos\n                   | empty\n    \n    metodos_opt : RETA metodos\n                | empty\n    empty :metodos : metodo\n    | metodos metodometodo : PRIVACIDADE VARIAVEL ABRE_PAR FECHA_PAR PONTO_VIRGULA\n              | PRIVACIDADE VARIAVEL ABRE_PAR VARIAVEL FECHA_PAR PONTO_VIRGULAatributos : atributo\n    | atributos atributoatributo : PRIVACIDADE TIPO DOIS_PONTOS VARIAVEL PONTO_VIRGULA\n                | PRIVACIDADE LIST MENORQ VARIAVEL MAIORQ DOIS_PONTOS VARIAVEL PONTO_VIRGULA'
    
_lr_action_items = {'TITULO':([0,],[3,]),'$end':([1,4,19,],[0,-1,-3,]),'MENORQ':([2,5,18,37,],[5,7,-2,42,]),'DOIS_PONTOS':([3,14,35,50,],[6,18,40,52,]),'VARIAVEL':([6,9,11,12,16,26,34,38,40,41,42,52,],[8,13,13,-4,-5,36,36,-6,43,44,46,53,]),'PALAVRA_CLASSES':([7,],[9,]),'DIAGRAMA':([8,],[10,]),'GERAL':([10,],[14,]),'MAIORQ':([11,12,15,16,38,46,],[15,-4,19,-5,-6,50,]),'ABRE_PAR':([13,36,],[17,41,]),'FECHA_PAR':([17,20,21,22,23,24,25,28,29,31,33,39,41,44,47,49,51,54,],[-12,27,-12,-8,-9,-17,-13,-7,-18,-11,-14,-10,45,48,-19,-15,-16,-20,]),'PRIVACIDADE':([17,21,22,24,25,29,30,33,39,47,49,51,54,],[26,32,34,-17,-13,-18,34,-14,34,-19,-15,-16,-20,]),'RETA':([21,24,29,47,54,],[30,-17,-18,-19,-20,]),'TIPO':([26,32,],[35,35,]),'LIST':([26,32,],[37,37,]),'PONTO_VIRGULA':([27,43,45,48,53,],[38,47,49,51,54,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'comeco':([0,],[2,]),'iniClasses':([2,],[4,]),'classes':([9,],[11,]),'classe':([9,11,],[12,16,]),'interno_classe':([17,],[20,]),'atributos':([17,],[21,]),'metodos':([17,30,],[22,39,]),'empty':([17,21,],[23,31,]),'atributo':([17,21,],[24,29,]),'metodo':([17,22,30,39,],[25,33,25,33,]),'metodos_opt':([21,],[28,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> comeco iniClasses','program',2,'p_def_program','parser_classe.py',232),
  ('comeco -> TITULO DOIS_PONTOS VARIAVEL DIAGRAMA GERAL DOIS_PONTOS','comeco',6,'p_def_comeco','parser_classe.py',237),
  ('iniClasses -> MENORQ MENORQ PALAVRA_CLASSES classes MAIORQ MAIORQ','iniClasses',6,'p_def_iniClasses','parser_classe.py',278),
  ('classes -> classe','classes',1,'p_def_classes','parser_classe.py',282),
  ('classes -> classes classe','classes',2,'p_def_classes','parser_classe.py',283),
  ('classe -> VARIAVEL ABRE_PAR interno_classe FECHA_PAR PONTO_VIRGULA','classe',5,'p_def_classe','parser_classe.py',290),
  ('interno_classe -> atributos metodos_opt','interno_classe',2,'p_interno_classe','parser_classe.py',295),
  ('interno_classe -> metodos','interno_classe',1,'p_interno_classe','parser_classe.py',296),
  ('interno_classe -> empty','interno_classe',1,'p_interno_classe','parser_classe.py',297),
  ('metodos_opt -> RETA metodos','metodos_opt',2,'p_metodos_opt','parser_classe.py',308),
  ('metodos_opt -> empty','metodos_opt',1,'p_metodos_opt','parser_classe.py',309),
  ('empty -> <empty>','empty',0,'p_empty','parser_classe.py',317),
  ('metodos -> metodo','metodos',1,'p_def_metodos','parser_classe.py',321),
  ('metodos -> metodos metodo','metodos',2,'p_def_metodos','parser_classe.py',322),
  ('metodo -> PRIVACIDADE VARIAVEL ABRE_PAR FECHA_PAR PONTO_VIRGULA','metodo',5,'p_def_metodo','parser_classe.py',329),
  ('metodo -> PRIVACIDADE VARIAVEL ABRE_PAR VARIAVEL FECHA_PAR PONTO_VIRGULA','metodo',6,'p_def_metodo','parser_classe.py',330),
  ('atributos -> atributo','atributos',1,'p_def_atributos','parser_classe.py',337),
  ('atributos -> atributos atributo','atributos',2,'p_def_atributos','parser_classe.py',338),
  ('atributo -> PRIVACIDADE TIPO DOIS_PONTOS VARIAVEL PONTO_VIRGULA','atributo',5,'p_def_atributo','parser_classe.py',345),
  ('atributo -> PRIVACIDADE LIST MENORQ VARIAVEL MAIORQ DOIS_PONTOS VARIAVEL PONTO_VIRGULA','atributo',8,'p_def_atributo','parser_classe.py',346),
]
