
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABRE_PAR CARD_UM CARD_UM_VARIOS CARD_VARIOS CARD_ZERO_UM CARD_ZERO_VARIOS CLASSES DIAGRAMA DOIS_PONTOS FECHA_PAR MAIORQ MENORQ PONTO_VIRGULA PRIVACIDADE RELACOES REL_AGREGACAO_DIR REL_AGREGRACAO_ESQ REL_ASSOCIACAO_DIR REL_ASSOCIACAO_ESQ REL_COMPOSICAO_DIR REL_COMPOSICAO_ESQ REL_DEPENDENCIA_DIR REL_DEPENDENCIA_ESQ REL_HERANCA_DIR REL_HERANCA_ESQ REL_REALIZACAO_DIR REL_REALIZACAO_ESQ REL_SOLIDA REL_TRACEJADA RETA TIPO TITULO VARIAVEL VIRGULAprogram : titletitle : TITULO DOIS_PONTOS VARIAVEL'
    
_lr_action_items = {'TITULO':([0,],[3,]),'$end':([1,2,5,],[0,-1,-2,]),'DOIS_PONTOS':([3,],[4,]),'VARIAVEL':([4,],[5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'title':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> title','program',1,'p_def_program','sagui_parser.py',175),
  ('title -> TITULO DOIS_PONTOS VARIAVEL','title',3,'p_def_tile','sagui_parser.py',179),
]
