
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'APAR FPAR PESSOA SON VIRprog : relacoesrelacoes : relacao\n    | relacoes relacaorelacao : SON APAR PESSOA VIR PESSOA FPAR'
    
_lr_action_items = {'SON':([0,2,3,5,10,],[4,4,-2,-3,-4,]),'$end':([1,2,3,5,10,],[0,-1,-2,-3,-4,]),'APAR':([4,],[6,]),'PESSOA':([6,8,],[7,9,]),'VIR':([7,],[8,]),'FPAR':([9,],[10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'prog':([0,],[1,]),'relacoes':([0,],[2,]),'relacao':([0,2,],[3,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> prog","S'",1,None,None,None),
  ('prog -> relacoes','prog',1,'p_def_prog','Ex3.py',26),
  ('relacoes -> relacao','relacoes',1,'p_def_relacoes','Ex3.py',30),
  ('relacoes -> relacoes relacao','relacoes',2,'p_def_relacoes','Ex3.py',31),
  ('relacao -> SON APAR PESSOA VIR PESSOA FPAR','relacao',6,'p_def_relacao','Ex3.py',34),
]
